### ISSUE TITLE
Expose PjInfo struct

### ISSUE THREAD

**Issue by frewsxcv** [georust/proj#131]
I'd like to have access to all those values, and seems simple enough just to expose it publicly

**Comment by urschrei** [comment]
Do you mean something different from https://docs.rs/proj/0.26.0/proj/struct.Projinfo.html?

**Comment by frewsxcv** [comment]
https://github.com/georust/proj/blob/fc5cf1cdf6f12c9c92973444285371159fcdb2e4/src/proj.rs#L1023-L1029

`ProjInfo` describes the PROJ installation, whereas `PjInfo` describes a specified CRS

**Comment by urschrei** [comment]
Ohhhh
