### ISSUE TITLE
Clarify "network" feature is required for TIFF support

### ISSUE THREAD

**Issue by burleight** [georust/proj#140]
> network: exposes APIs which, when enabled, can fetch grid data from the internet to improve projection accuracy. See [enable_network](https://docs.rs/proj/latest/proj/struct.ProjBuilder.html#method.enable_network) for details.

Should this be edited to clarify that if the "network" feature isn't enabled, TIFF support is disabled?

Or could TIFF support be enabled, even if network isn't?

**Comment by urschrei** [comment]
We can probably add an explicit tiff feature. I think the reason it's currently set up like this is that we thought the primary use case for tiff support was reading grid info from remote COGs. What can you do with local-only tiff support?

**Comment by burleight** [comment]
I've building the tiff files I need into a docker image alongside a service which uses this crate.
