### ISSUE TITLE
repo maintenance: tag historical releases, disambiguate proj vs. proj-sys tags

### ISSUE THREAD

**Issue by michaelkirk** [georust/proj#48]
One thing I didn't think through - now that proj and proj-sys share a repo, I think we should adopt a tagging scheme like geo's.

Specifically, instead of tagging '1.2.3' we'll need to be clear which crate the tag applies to. e.g. `proj-1.2.3` vs. `proj-sys-2.3.4`

If this is agreeable, I can go through the chore of adding a new explicit tag for the pre-existing tags. 

Even though they're potentially ambiguous, I think it's probably best to leave the old tags as they were, since deleting old tags might surprise people. WDYT?

**Comment by urschrei** [comment]
- Good idea
- I've done it
- Old tags are left in place

**Comment by urschrei** [comment]
Also pushed new tags (`proj-0.20.5`, `proj-sys-0.18.3`) to bring us up to date with crates.io versions

**Comment by michaelkirk** [comment]
Oh excellent - thank you @urschrei!
